const teamsData = [
  {
    "name": "Mumbai Indians",
    "shortName": "MI",
    "initialPurse": 1200000000,
    "remainingPurse": 1200000000,
    "primaryColor": "#004ba0",
    "secondaryColor": "#d1ab3e",
    "logo": "/logos/mi.svg"
  },
  {
    "name": "Chennai Super Kings",
    "shortName": "CSK",
    "initialPurse": 1200000000,
    "remainingPurse": 1200000000,
    "primaryColor": "#fdb913",
    "secondaryColor": "#0081e9",
    "logo": "/logos/csk.svg"
  },
  {
    "name": "Royal Challengers Bengaluru",
    "shortName": "RCB",
    "initialPurse": 1200000000,
    "remainingPurse": 1200000000,
    "primaryColor": "#d71920",
    "secondaryColor": "#000000",
    "logo": "/logos/rcb.svg"
  },
  {
    "name": "Sunrisers Hyderabad",
    "shortName": "SRH",
    "initialPurse": 1200000000,
    "remainingPurse": 1200000000,
    "primaryColor": "#f26522",
    "secondaryColor": "#000000",
    "logo": "/logos/srh.svg"
  },
  {
    "name": "Delhi Capitals",
    "shortName": "DC",
    "initialPurse": 1200000000,
    "remainingPurse": 1200000000,
    "primaryColor": "#004c97",
    "secondaryColor": "#d71920",
    "logo": "/logos/dc.svg"
  },
  {
    "name": "Kolkata Knight Riders",
    "shortName": "KKR",
    "initialPurse": 1200000000,
    "remainingPurse": 1200000000,
    "primaryColor": "#3a225d",
    "secondaryColor": "#ecc542",
    "logo": "/logos/kkr.svg"
  },
  {
    "name": "Rajasthan Royals",
    "shortName": "RR",
    "initialPurse": 1200000000,
    "remainingPurse": 1200000000,
    "primaryColor": "#ea1a85",
    "secondaryColor": "#254aa5",
    "logo": "/logos/rr.svg"
  },
  {
    "name": "Punjab Kings",
    "shortName": "PBKS",
    "initialPurse": 1200000000,
    "remainingPurse": 1200000000,
    "primaryColor": "#ed1b24",
    "secondaryColor": "#c0c0c0",
    "logo": "/logos/pbks.svg"
  },
  {
    "name": "Gujarat Titans",
    "shortName": "GT",
    "initialPurse": 1200000000,
    "remainingPurse": 1200000000,
    "primaryColor": "#1b2133",
    "secondaryColor": "#bf9b30",
    "logo": "/logos/gt.svg"
  },
  {
    "name": "Lucknow Super Giants",
    "shortName": "LSG",
    "initialPurse": 1200000000,
    "remainingPurse": 1200000000,
    "primaryColor": "#0057e7",
    "secondaryColor": "#f36f21",
    "logo": "/logos/lsg.svg"
  }
];

const playersData = [
  {
    "name": "Virat Kohli",
    "country": "India",
    "isOverseas": false,
    "role": "BATTER",
    "category": "MARQUEE",
    "isCapped": true,
    "auctionSet": "M1",
    "bowlingType": "NONE",
    "battingPosition": "TOP_ORDER",
    "age": 35,
    "battingStyle": "Right-hand classical bat",
    "bowlingStyle": "Right-arm medium",
    "basePrice": 20000000,
    "image": "/players/virat-kohli.jpg",
    "stats": {
      "matches": 252,
      "runs": 8004,
      "highestScore": "113*",
      "wickets": 4,
      "bestBowling": "2/25",
      "strikeRate": 131.9,
      "economy": 8.8
    }
  },
  {
    "name": "Rohit Sharma",
    "country": "India",
    "isOverseas": false,
    "role": "BATTER",
    "category": "MARQUEE",
    "isCapped": true,
    "auctionSet": "M1",
    "bowlingType": "NONE",
    "battingPosition": "TOP_ORDER",
    "age": 37,
    "battingStyle": "Right-hand opening master",
    "bowlingStyle": "Right-arm offbreak",
    "basePrice": 20000000,
    "image": "/players/rohit-sharma.jpg",
    "stats": {
      "matches": 257,
      "runs": 6628,
      "highestScore": "109*",
      "wickets": 15,
      "bestBowling": "4/6",
      "strikeRate": 131.1,
      "economy": 8
    }
  },
  {
    "name": "MS Dhoni",
    "country": "India",
    "isOverseas": false,
    "role": "WICKET_KEEPER",
    "category": "MARQUEE",
    "isCapped": true,
    "auctionSet": "M1",
    "bowlingType": "NONE",
    "battingPosition": "FINISHER",
    "age": 42,
    "battingStyle": "Right-hand legendary finisher",
    "bowlingStyle": "Right-arm medium",
    "basePrice": 20000000,
    "image": "/players/ms-dhoni.jpg",
    "stats": {
      "matches": 264,
      "runs": 5243,
      "highestScore": "84*",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 137.5,
      "economy": 0
    }
  },
  {
    "name": "Jasprit Bumrah",
    "country": "India",
    "isOverseas": false,
    "role": "BOWLER",
    "category": "MARQUEE",
    "isCapped": true,
    "auctionSet": "M1",
    "bowlingType": "PACE",
    "battingPosition": "LOWER_ORDER",
    "age": 30,
    "battingStyle": "Right-hand bat",
    "bowlingStyle": "Right-arm fast (Yorker King)",
    "basePrice": 20000000,
    "image": "/players/jasprit-bumrah.jpg",
    "stats": {
      "matches": 133,
      "runs": 69,
      "highestScore": "16*",
      "wickets": 165,
      "bestBowling": "5/10",
      "strikeRate": 78,
      "economy": 7.3
    }
  },
  {
    "name": "Hardik Pandya",
    "country": "India",
    "isOverseas": false,
    "role": "ALL_ROUNDER",
    "category": "MARQUEE",
    "isCapped": true,
    "auctionSet": "M1",
    "bowlingType": "PACE",
    "battingPosition": "MIDDLE_ORDER",
    "age": 30,
    "battingStyle": "Right-hand explosive hitter",
    "bowlingStyle": "Right-arm fast-medium",
    "basePrice": 20000000,
    "image": "/players/hardik-pandya.jpg",
    "stats": {
      "matches": 137,
      "runs": 2525,
      "highestScore": "91",
      "wickets": 64,
      "bestBowling": "3/17",
      "strikeRate": 145.9,
      "economy": 8.94
    }
  },
  {
    "name": "Pat Cummins",
    "country": "Australia",
    "isOverseas": true,
    "role": "ALL_ROUNDER",
    "category": "MARQUEE",
    "isCapped": true,
    "auctionSet": "M1",
    "bowlingType": "PACE",
    "battingPosition": "LOWER_ORDER",
    "age": 31,
    "battingStyle": "Right-hand power striker",
    "bowlingStyle": "Right-arm fast",
    "basePrice": 20000000,
    "image": "/players/pat-cummins.jpg",
    "stats": {
      "matches": 58,
      "runs": 515,
      "highestScore": "66*",
      "wickets": 63,
      "bestBowling": "4/34",
      "strikeRate": 148,
      "economy": 8.65
    }
  },
  {
    "name": "Suryakumar Yadav",
    "country": "India",
    "isOverseas": false,
    "role": "BATTER",
    "category": "MARQUEE",
    "isCapped": true,
    "auctionSet": "M2",
    "bowlingType": "NONE",
    "battingPosition": "TOP_ORDER",
    "age": 33,
    "battingStyle": "Right-hand 360-degree innovation",
    "bowlingStyle": "Right-arm offbreak",
    "basePrice": 20000000,
    "image": "/players/suryakumar-yadav.jpg",
    "stats": {
      "matches": 150,
      "runs": 3594,
      "highestScore": "103*",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 145.3,
      "economy": 0
    }
  },
  {
    "name": "Rishabh Pant",
    "country": "India",
    "isOverseas": false,
    "role": "WICKET_KEEPER",
    "category": "MARQUEE",
    "isCapped": true,
    "auctionSet": "M2",
    "bowlingType": "NONE",
    "battingPosition": "MIDDLE_ORDER",
    "age": 26,
    "battingStyle": "Left-hand fearless matchwinner",
    "bowlingStyle": "Right-arm medium",
    "basePrice": 20000000,
    "image": "/players/rishabh-pant.jpg",
    "stats": {
      "matches": 111,
      "runs": 3284,
      "highestScore": "128*",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 148.9,
      "economy": 0
    }
  },
  {
    "name": "Mitchell Starc",
    "country": "Australia",
    "isOverseas": true,
    "role": "BOWLER",
    "category": "MARQUEE",
    "isCapped": true,
    "auctionSet": "M2",
    "bowlingType": "PACE",
    "battingPosition": "LOWER_ORDER",
    "age": 34,
    "battingStyle": "Left-hand bat",
    "bowlingStyle": "Left-arm express fast",
    "basePrice": 20000000,
    "image": "/players/mitchell-starc.jpg",
    "stats": {
      "matches": 41,
      "runs": 112,
      "highestScore": "29",
      "wickets": 51,
      "bestBowling": "4/15",
      "strikeRate": 105,
      "economy": 7.98
    }
  },
  {
    "name": "Heinrich Klaasen",
    "country": "South Africa",
    "isOverseas": true,
    "role": "WICKET_KEEPER",
    "category": "MARQUEE",
    "isCapped": true,
    "auctionSet": "M2",
    "bowlingType": "NONE",
    "battingPosition": "MIDDLE_ORDER",
    "age": 32,
    "battingStyle": "Right-hand elite spin destroyer",
    "bowlingStyle": "Right-arm offbreak",
    "basePrice": 20000000,
    "image": "/players/heinrich-klaasen.jpg",
    "stats": {
      "matches": 35,
      "runs": 993,
      "highestScore": "104",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 168.3,
      "economy": 0
    }
  },
  {
    "name": "Rashid Khan",
    "country": "Afghanistan",
    "isOverseas": true,
    "role": "BOWLER",
    "category": "MARQUEE",
    "isCapped": true,
    "auctionSet": "M2",
    "bowlingType": "SPIN",
    "battingPosition": "LOWER_ORDER",
    "age": 25,
    "battingStyle": "Right-hand snake-shot striker",
    "bowlingStyle": "Right-arm rapid legbreak googly",
    "basePrice": 20000000,
    "image": "/players/rashid-khan.jpg",
    "stats": {
      "matches": 121,
      "runs": 545,
      "highestScore": "79*",
      "wickets": 149,
      "bestBowling": "4/24",
      "strikeRate": 154.8,
      "economy": 6.82
    }
  },
  {
    "name": "Jos Buttler",
    "country": "England",
    "isOverseas": true,
    "role": "WICKET_KEEPER",
    "category": "MARQUEE",
    "isCapped": true,
    "auctionSet": "M2",
    "bowlingType": "NONE",
    "battingPosition": "TOP_ORDER",
    "age": 33,
    "battingStyle": "Right-hand destructive opener",
    "bowlingStyle": "None",
    "basePrice": 20000000,
    "image": "/players/jos-buttler.jpg",
    "stats": {
      "matches": 107,
      "runs": 3582,
      "highestScore": "124",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 147.5,
      "economy": 0
    }
  },
  {
    "name": "Shubman Gill",
    "country": "India",
    "isOverseas": false,
    "role": "BATTER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "BA1",
    "bowlingType": "NONE",
    "battingPosition": "TOP_ORDER",
    "age": 24,
    "battingStyle": "Right-hand elegant strokeplay",
    "bowlingStyle": "Right-arm offbreak",
    "basePrice": 20000000,
    "image": "/players/shubman-gill.jpg",
    "stats": {
      "matches": 103,
      "runs": 3216,
      "highestScore": "129",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 135.7,
      "economy": 0
    }
  },
  {
    "name": "Yashasvi Jaiswal",
    "country": "India",
    "isOverseas": false,
    "role": "BATTER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "BA1",
    "bowlingType": "NONE",
    "battingPosition": "TOP_ORDER",
    "age": 22,
    "battingStyle": "Left-hand aggressive prodigy",
    "bowlingStyle": "Right-arm legbreak",
    "basePrice": 20000000,
    "image": "/players/yashasvi-jaiswal.jpg",
    "stats": {
      "matches": 52,
      "runs": 1607,
      "highestScore": "124",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 150.6,
      "economy": 0
    }
  },
  {
    "name": "Shreyas Iyer",
    "country": "India",
    "isOverseas": false,
    "role": "BATTER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "BA1",
    "bowlingType": "NONE",
    "battingPosition": "TOP_ORDER",
    "age": 29,
    "battingStyle": "Right-hand authoritative captain",
    "bowlingStyle": "Right-arm legbreak",
    "basePrice": 20000000,
    "image": "/players/shreyas-iyer.jpg",
    "stats": {
      "matches": 115,
      "runs": 3127,
      "highestScore": "96",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 127.5,
      "economy": 0
    }
  },
  {
    "name": "Travis Head",
    "country": "Australia",
    "isOverseas": true,
    "role": "BATTER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "BA1",
    "bowlingType": "NONE",
    "battingPosition": "TOP_ORDER",
    "age": 30,
    "battingStyle": "Left-hand powerplay hurricane",
    "bowlingStyle": "Right-arm offbreak",
    "basePrice": 20000000,
    "image": "/players/travis-head.jpg",
    "stats": {
      "matches": 25,
      "runs": 772,
      "highestScore": "102",
      "wickets": 3,
      "bestBowling": "2/12",
      "strikeRate": 178.4,
      "economy": 8.9
    }
  },
  {
    "name": "Ruturaj Gaikwad",
    "country": "India",
    "isOverseas": false,
    "role": "BATTER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "BA1",
    "bowlingType": "NONE",
    "battingPosition": "TOP_ORDER",
    "age": 27,
    "battingStyle": "Right-hand fluent anchor",
    "bowlingStyle": "Right-arm offbreak",
    "basePrice": 20000000,
    "image": "/players/ruturaj-gaikwad.jpg",
    "stats": {
      "matches": 66,
      "runs": 2380,
      "highestScore": "108*",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 136.9,
      "economy": 0
    }
  },
  {
    "name": "David Miller",
    "country": "South Africa",
    "isOverseas": true,
    "role": "BATTER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "BA1",
    "bowlingType": "NONE",
    "battingPosition": "FINISHER",
    "age": 35,
    "battingStyle": "Left-hand killer finisher",
    "bowlingStyle": "Right-arm offbreak",
    "basePrice": 15000000,
    "image": "/players/david-miller.jpg",
    "stats": {
      "matches": 130,
      "runs": 2924,
      "highestScore": "101*",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 139.3,
      "economy": 0
    }
  },
  {
    "name": "Rinku Singh",
    "country": "India",
    "isOverseas": false,
    "role": "BATTER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "BA2",
    "bowlingType": "NONE",
    "battingPosition": "FINISHER",
    "age": 26,
    "battingStyle": "Left-hand miraculous finisher",
    "bowlingStyle": "Right-arm offbreak",
    "basePrice": 15000000,
    "image": "/players/rinku-singh.jpg",
    "stats": {
      "matches": 45,
      "runs": 893,
      "highestScore": "67*",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 143.3,
      "economy": 0
    }
  },
  {
    "name": "Tilak Varma",
    "country": "India",
    "isOverseas": false,
    "role": "BATTER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "BA2",
    "bowlingType": "NONE",
    "battingPosition": "MIDDLE_ORDER",
    "age": 21,
    "battingStyle": "Left-hand stylish left-hander",
    "bowlingStyle": "Right-arm offbreak",
    "basePrice": 10000000,
    "image": "/players/tilak-varma.jpg",
    "stats": {
      "matches": 38,
      "runs": 1156,
      "highestScore": "84*",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 146.3,
      "economy": 0
    }
  },
  {
    "name": "Faf du Plessis",
    "country": "South Africa",
    "isOverseas": true,
    "role": "BATTER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "BA2",
    "bowlingType": "NONE",
    "battingPosition": "TOP_ORDER",
    "age": 39,
    "battingStyle": "Right-hand warrior opener",
    "bowlingStyle": "Right-arm legbreak",
    "basePrice": 20000000,
    "image": "/players/faf-du-plessis.jpg",
    "stats": {
      "matches": 145,
      "runs": 4571,
      "highestScore": "96",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 136.4,
      "economy": 0
    }
  },
  {
    "name": "David Warner",
    "country": "Australia",
    "isOverseas": true,
    "role": "BATTER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "BA2",
    "bowlingType": "NONE",
    "battingPosition": "TOP_ORDER",
    "age": 37,
    "battingStyle": "Left-hand pocket dynamite",
    "bowlingStyle": "Right-arm legbreak",
    "basePrice": 20000000,
    "image": "/players/david-warner.jpg",
    "stats": {
      "matches": 184,
      "runs": 6565,
      "highestScore": "126",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 139.8,
      "economy": 0
    }
  },
  {
    "name": "Rahul Tripathi",
    "country": "India",
    "isOverseas": false,
    "role": "BATTER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "BA2",
    "bowlingType": "NONE",
    "battingPosition": "TOP_ORDER",
    "age": 33,
    "battingStyle": "Right-hand dynamic pace hitter",
    "bowlingStyle": "Right-arm medium",
    "basePrice": 10000000,
    "image": "/players/rahul-tripathi.jpg",
    "stats": {
      "matches": 95,
      "runs": 2236,
      "highestScore": "93",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 139.5,
      "economy": 0
    }
  },
  {
    "name": "Dewald Brevis",
    "country": "South Africa",
    "isOverseas": true,
    "role": "BATTER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "BA2",
    "bowlingType": "SPIN",
    "battingPosition": "MIDDLE_ORDER",
    "age": 21,
    "battingStyle": "Right-hand 360-degree Baby AB power striker",
    "bowlingStyle": "Right-arm legbreak",
    "basePrice": 7500000,
    "image": "/players/dewald-brevis.png",
    "stats": {
      "matches": 10,
      "runs": 230,
      "highestScore": "49",
      "wickets": 1,
      "bestBowling": "1/8",
      "strikeRate": 142,
      "economy": 9.1
    }
  },
  {
    "name": "KL Rahul",
    "country": "India",
    "isOverseas": false,
    "role": "WICKET_KEEPER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "WK1",
    "bowlingType": "NONE",
    "battingPosition": "TOP_ORDER",
    "age": 32,
    "battingStyle": "Right-hand classical matchwinner",
    "bowlingStyle": "Right-arm medium",
    "basePrice": 20000000,
    "image": "/players/kl-rahul.jpg",
    "stats": {
      "matches": 132,
      "runs": 4683,
      "highestScore": "132*",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 134.6,
      "economy": 0
    }
  },
  {
    "name": "Sanju Samson",
    "country": "India",
    "isOverseas": false,
    "role": "WICKET_KEEPER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "WK1",
    "bowlingType": "NONE",
    "battingPosition": "TOP_ORDER",
    "age": 29,
    "battingStyle": "Right-hand effortless six hitter",
    "bowlingStyle": "Right-arm offbreak",
    "basePrice": 20000000,
    "image": "/players/sanju-samson.jpg",
    "stats": {
      "matches": 167,
      "runs": 4419,
      "highestScore": "119",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 138.9,
      "economy": 0
    }
  },
  {
    "name": "Nicholas Pooran",
    "country": "West Indies",
    "isOverseas": true,
    "role": "WICKET_KEEPER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "WK1",
    "bowlingType": "NONE",
    "battingPosition": "MIDDLE_ORDER",
    "age": 28,
    "battingStyle": "Left-hand monster six hitter",
    "bowlingStyle": "Right-arm offbreak",
    "basePrice": 20000000,
    "image": "/players/nicholas-pooran.jpg",
    "stats": {
      "matches": 76,
      "runs": 1769,
      "highestScore": "77",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 162.3,
      "economy": 0
    }
  },
  {
    "name": "Quinton de Kock",
    "country": "South Africa",
    "isOverseas": true,
    "role": "WICKET_KEEPER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "WK1",
    "bowlingType": "NONE",
    "battingPosition": "TOP_ORDER",
    "age": 31,
    "battingStyle": "Left-hand aggressive opener",
    "bowlingStyle": "None",
    "basePrice": 20000000,
    "image": "/players/quinton-de-kock.jpg",
    "stats": {
      "matches": 107,
      "runs": 3157,
      "highestScore": "140*",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 134.2,
      "economy": 0
    }
  },
  {
    "name": "Ishan Kishan",
    "country": "India",
    "isOverseas": false,
    "role": "WICKET_KEEPER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "WK2",
    "bowlingType": "NONE",
    "battingPosition": "TOP_ORDER",
    "age": 25,
    "battingStyle": "Left-hand pocket dynamo opener",
    "bowlingStyle": "Right-arm legbreak",
    "basePrice": 20000000,
    "image": "/players/ishan-kishan.jpg",
    "stats": {
      "matches": 105,
      "runs": 2644,
      "highestScore": "99",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 135.9,
      "economy": 0
    }
  },
  {
    "name": "Phil Salt",
    "country": "England",
    "isOverseas": true,
    "role": "WICKET_KEEPER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "WK2",
    "bowlingType": "NONE",
    "battingPosition": "TOP_ORDER",
    "age": 27,
    "battingStyle": "Right-hand firebrand opener",
    "bowlingStyle": "None",
    "basePrice": 15000000,
    "image": "/players/phil-salt.png",
    "stats": {
      "matches": 21,
      "runs": 653,
      "highestScore": "89*",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 175.5,
      "economy": 0
    }
  },
  {
    "name": "Dhruv Jurel",
    "country": "India",
    "isOverseas": false,
    "role": "WICKET_KEEPER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "WK2",
    "bowlingType": "NONE",
    "battingPosition": "FINISHER",
    "age": 23,
    "battingStyle": "Right-hand clutch performer",
    "bowlingStyle": "None",
    "basePrice": 10000000,
    "image": "/players/dhruv-jurel.jpg",
    "stats": {
      "matches": 28,
      "runs": 347,
      "highestScore": "56*",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 151.5,
      "economy": 0
    }
  },
  {
    "name": "Ravindra Jadeja",
    "country": "India",
    "isOverseas": false,
    "role": "ALL_ROUNDER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "AL1",
    "bowlingType": "SPIN",
    "battingPosition": "MIDDLE_ORDER",
    "age": 35,
    "battingStyle": "Left-hand sword celebration hitter",
    "bowlingStyle": "Slow left-arm orthodox wizard",
    "basePrice": 20000000,
    "image": "/players/ravindra-jadeja.jpg",
    "stats": {
      "matches": 240,
      "runs": 2959,
      "highestScore": "62*",
      "wickets": 160,
      "bestBowling": "5/16",
      "strikeRate": 129.6,
      "economy": 7.6
    }
  },
  {
    "name": "Sunil Narine",
    "country": "West Indies",
    "isOverseas": true,
    "role": "ALL_ROUNDER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "AL1",
    "bowlingType": "SPIN",
    "battingPosition": "TOP_ORDER",
    "age": 36,
    "battingStyle": "Left-hand pinch hitting beast",
    "bowlingStyle": "Right-arm mystery offspin",
    "basePrice": 20000000,
    "image": "/players/sunil-narine.jpg",
    "stats": {
      "matches": 177,
      "runs": 1534,
      "highestScore": "109",
      "wickets": 180,
      "bestBowling": "5/19",
      "strikeRate": 165.8,
      "economy": 6.73
    }
  },
  {
    "name": "Andre Russell",
    "country": "West Indies",
    "isOverseas": true,
    "role": "ALL_ROUNDER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "AL1",
    "bowlingType": "PACE",
    "battingPosition": "FINISHER",
    "age": 36,
    "battingStyle": "Right-hand supreme muscle hitter",
    "bowlingStyle": "Right-arm heavy fast",
    "basePrice": 20000000,
    "image": "/players/andre-russell.jpg",
    "stats": {
      "matches": 127,
      "runs": 2484,
      "highestScore": "88*",
      "wickets": 115,
      "bestBowling": "5/15",
      "strikeRate": 174.9,
      "economy": 9.32
    }
  },
  {
    "name": "Glenn Maxwell",
    "country": "Australia",
    "isOverseas": true,
    "role": "ALL_ROUNDER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "AL1",
    "bowlingType": "SPIN",
    "battingPosition": "MIDDLE_ORDER",
    "age": 35,
    "battingStyle": "Right-hand reverse sweep artist",
    "bowlingStyle": "Right-arm offbreak",
    "basePrice": 20000000,
    "image": "/players/glenn-maxwell.jpg",
    "stats": {
      "matches": 134,
      "runs": 2771,
      "highestScore": "95",
      "wickets": 37,
      "bestBowling": "2/15",
      "strikeRate": 156.7,
      "economy": 8.3
    }
  },
  {
    "name": "Sam Curran",
    "country": "England",
    "isOverseas": true,
    "role": "ALL_ROUNDER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "AL1",
    "bowlingType": "PACE",
    "battingPosition": "MIDDLE_ORDER",
    "age": 26,
    "battingStyle": "Left-hand aggressive strokeplayer",
    "bowlingStyle": "Left-arm medium-fast swing",
    "basePrice": 20000000,
    "image": "/players/sam-curran.png",
    "stats": {
      "matches": 59,
      "runs": 883,
      "highestScore": "63",
      "wickets": 58,
      "bestBowling": "4/11",
      "strikeRate": 138.8,
      "economy": 9.48
    }
  },
  {
    "name": "Axar Patel",
    "country": "India",
    "isOverseas": false,
    "role": "ALL_ROUNDER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "AL2",
    "bowlingType": "SPIN",
    "battingPosition": "MIDDLE_ORDER",
    "age": 30,
    "battingStyle": "Left-hand dependable crisis batter",
    "bowlingStyle": "Slow left-arm dart spinner",
    "basePrice": 15000000,
    "image": "/players/axar-patel.jpg",
    "stats": {
      "matches": 150,
      "runs": 1653,
      "highestScore": "66",
      "wickets": 123,
      "bestBowling": "4/21",
      "strikeRate": 130.8,
      "economy": 7.24
    }
  },
  {
    "name": "Marcus Stoinis",
    "country": "Australia",
    "isOverseas": true,
    "role": "ALL_ROUNDER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "AL2",
    "bowlingType": "PACE",
    "battingPosition": "MIDDLE_ORDER",
    "age": 34,
    "battingStyle": "Right-hand power striker",
    "bowlingStyle": "Right-arm medium",
    "basePrice": 15000000,
    "image": "/players/marcus-stoinis.jpg",
    "stats": {
      "matches": 96,
      "runs": 1866,
      "highestScore": "124*",
      "wickets": 43,
      "bestBowling": "4/15",
      "strikeRate": 142.1,
      "economy": 9.38
    }
  },
  {
    "name": "Shivam Dube",
    "country": "India",
    "isOverseas": false,
    "role": "ALL_ROUNDER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "AL2",
    "bowlingType": "PACE",
    "battingPosition": "MIDDLE_ORDER",
    "age": 31,
    "battingStyle": "Left-hand towering six machine",
    "bowlingStyle": "Right-arm medium",
    "basePrice": 15000000,
    "image": "/players/shivam-dube.jpg",
    "stats": {
      "matches": 65,
      "runs": 1502,
      "highestScore": "95*",
      "wickets": 5,
      "bestBowling": "2/15",
      "strikeRate": 159.2,
      "economy": 8.9
    }
  },
  {
    "name": "Nitish Kumar Reddy",
    "country": "India",
    "isOverseas": false,
    "role": "ALL_ROUNDER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "AL2",
    "bowlingType": "PACE",
    "battingPosition": "MIDDLE_ORDER",
    "age": 21,
    "battingStyle": "Right-hand fearless young all-rounder",
    "bowlingStyle": "Right-arm medium-fast",
    "basePrice": 10000000,
    "image": "/players/nitish-kumar-reddy.jpg",
    "stats": {
      "matches": 15,
      "runs": 303,
      "highestScore": "76*",
      "wickets": 3,
      "bestBowling": "2/17",
      "strikeRate": 142.9,
      "economy": 9.2
    }
  },
  {
    "name": "Mohammed Shami",
    "country": "India",
    "isOverseas": false,
    "role": "BOWLER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "FA1",
    "bowlingType": "PACE",
    "battingPosition": "LOWER_ORDER",
    "age": 33,
    "battingStyle": "Right-hand bat",
    "bowlingStyle": "Right-arm seam & swing maestro",
    "basePrice": 20000000,
    "image": "/players/mohammed-shami.jpg",
    "stats": {
      "matches": 110,
      "runs": 79,
      "highestScore": "21",
      "wickets": 127,
      "bestBowling": "4/11",
      "strikeRate": 85,
      "economy": 8.44
    }
  },
  {
    "name": "Trent Boult",
    "country": "New Zealand",
    "isOverseas": true,
    "role": "BOWLER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "FA1",
    "bowlingType": "PACE",
    "battingPosition": "LOWER_ORDER",
    "age": 34,
    "battingStyle": "Right-hand bat",
    "bowlingStyle": "Left-arm lethal powerplay swing",
    "basePrice": 20000000,
    "image": "/players/trent-boult.jpg",
    "stats": {
      "matches": 104,
      "runs": 47,
      "highestScore": "17",
      "wickets": 121,
      "bestBowling": "4/18",
      "strikeRate": 81,
      "economy": 8.29
    }
  },
  {
    "name": "Kagiso Rabada",
    "country": "South Africa",
    "isOverseas": true,
    "role": "BOWLER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "FA1",
    "bowlingType": "PACE",
    "battingPosition": "LOWER_ORDER",
    "age": 29,
    "battingStyle": "Left-hand bat",
    "bowlingStyle": "Right-arm thunderbolt fast",
    "basePrice": 20000000,
    "image": "/players/kagiso-rabada.jpg",
    "stats": {
      "matches": 80,
      "runs": 186,
      "highestScore": "44",
      "wickets": 117,
      "bestBowling": "4/21",
      "strikeRate": 95,
      "economy": 8.42
    }
  },
  {
    "name": "Arshdeep Singh",
    "country": "India",
    "isOverseas": false,
    "role": "BOWLER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "FA1",
    "bowlingType": "PACE",
    "battingPosition": "LOWER_ORDER",
    "age": 25,
    "battingStyle": "Left-hand bat",
    "bowlingStyle": "Left-arm death yorker specialist",
    "basePrice": 15000000,
    "image": "/players/arshdeep-singh.jpg",
    "stats": {
      "matches": 65,
      "runs": 28,
      "highestScore": "10*",
      "wickets": 76,
      "bestBowling": "5/32",
      "strikeRate": 72,
      "economy": 8.74
    }
  },
  {
    "name": "Mohammed Siraj",
    "country": "India",
    "isOverseas": false,
    "role": "BOWLER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "FA1",
    "bowlingType": "PACE",
    "battingPosition": "LOWER_ORDER",
    "age": 30,
    "battingStyle": "Right-hand bat",
    "bowlingStyle": "Right-arm high pace swing (Miyan Magic)",
    "basePrice": 15000000,
    "image": "/players/mohammed-siraj.jpg",
    "stats": {
      "matches": 93,
      "runs": 110,
      "highestScore": "14*",
      "wickets": 93,
      "bestBowling": "4/21",
      "strikeRate": 88,
      "economy": 8.65
    }
  },
  {
    "name": "Matheesha Pathirana",
    "country": "Sri Lanka",
    "isOverseas": true,
    "role": "BOWLER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "FA2",
    "bowlingType": "PACE",
    "battingPosition": "LOWER_ORDER",
    "age": 21,
    "battingStyle": "Right-hand bat",
    "bowlingStyle": "Right-arm slinging 150km yorkers (Baby Malinga)",
    "basePrice": 10000000,
    "image": "/players/matheesha-pathirana.jpg",
    "stats": {
      "matches": 20,
      "runs": 4,
      "highestScore": "4*",
      "wickets": 34,
      "bestBowling": "4/28",
      "strikeRate": 60,
      "economy": 7.88
    }
  },
  {
    "name": "Bhuvneshwar Kumar",
    "country": "India",
    "isOverseas": false,
    "role": "BOWLER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "FA2",
    "bowlingType": "PACE",
    "battingPosition": "LOWER_ORDER",
    "age": 34,
    "battingStyle": "Right-hand bat",
    "bowlingStyle": "Right-arm swing king",
    "basePrice": 15000000,
    "image": "/players/bhuvneshwar-kumar.png",
    "stats": {
      "matches": 176,
      "runs": 309,
      "highestScore": "24*",
      "wickets": 181,
      "bestBowling": "5/19",
      "strikeRate": 86,
      "economy": 7.56
    }
  },
  {
    "name": "T Natarajan",
    "country": "India",
    "isOverseas": false,
    "role": "BOWLER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "FA2",
    "bowlingType": "PACE",
    "battingPosition": "LOWER_ORDER",
    "age": 33,
    "battingStyle": "Left-hand bat",
    "bowlingStyle": "Left-arm accurate yorker machine",
    "basePrice": 10000000,
    "image": "/players/t-natarajan.jpg",
    "stats": {
      "matches": 61,
      "runs": 7,
      "highestScore": "3*",
      "wickets": 67,
      "bestBowling": "4/19",
      "strikeRate": 55,
      "economy": 8.8
    }
  },
  {
    "name": "Yuzvendra Chahal",
    "country": "India",
    "isOverseas": false,
    "role": "BOWLER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "SP1",
    "bowlingType": "SPIN",
    "battingPosition": "LOWER_ORDER",
    "age": 33,
    "battingStyle": "Right-hand bat",
    "bowlingStyle": "Right-arm classical legbreak",
    "basePrice": 20000000,
    "image": "/players/yuzvendra-chahal.png",
    "stats": {
      "matches": 160,
      "runs": 47,
      "highestScore": "8*",
      "wickets": 205,
      "bestBowling": "5/40",
      "strikeRate": 50,
      "economy": 7.72
    }
  },
  {
    "name": "Kuldeep Yadav",
    "country": "India",
    "isOverseas": false,
    "role": "BOWLER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "SP1",
    "bowlingType": "SPIN",
    "battingPosition": "LOWER_ORDER",
    "age": 29,
    "battingStyle": "Left-hand bat",
    "bowlingStyle": "Left-arm unorthodox chinaman magic",
    "basePrice": 15000000,
    "image": "/players/kuldeep-yadav.jpg",
    "stats": {
      "matches": 84,
      "runs": 139,
      "highestScore": "35*",
      "wickets": 87,
      "bestBowling": "4/14",
      "strikeRate": 75,
      "economy": 8.12
    }
  },
  {
    "name": "Ravi Bishnoi",
    "country": "India",
    "isOverseas": false,
    "role": "BOWLER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "SP1",
    "bowlingType": "SPIN",
    "battingPosition": "LOWER_ORDER",
    "age": 23,
    "battingStyle": "Right-hand bat",
    "bowlingStyle": "Right-arm rapid googly spinner",
    "basePrice": 15000000,
    "image": "/players/ravi-bishnoi.jpg",
    "stats": {
      "matches": 66,
      "runs": 37,
      "highestScore": "15*",
      "wickets": 63,
      "bestBowling": "3/24",
      "strikeRate": 65,
      "economy": 7.8
    }
  },
  {
    "name": "Varun Chakravarthy",
    "country": "India",
    "isOverseas": false,
    "role": "BOWLER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "SP2",
    "bowlingType": "SPIN",
    "battingPosition": "LOWER_ORDER",
    "age": 32,
    "battingStyle": "Right-hand bat",
    "bowlingStyle": "Right-arm architect mystery spin",
    "basePrice": 15000000,
    "image": "/players/varun-chakravarthy.jpg",
    "stats": {
      "matches": 71,
      "runs": 31,
      "highestScore": "9*",
      "wickets": 83,
      "bestBowling": "5/20",
      "strikeRate": 55,
      "economy": 7.56
    }
  },
  {
    "name": "Ravichandran Ashwin",
    "country": "India",
    "isOverseas": false,
    "role": "BOWLER",
    "category": "CAPPED",
    "isCapped": true,
    "auctionSet": "SP2",
    "bowlingType": "SPIN",
    "battingPosition": "LOWER_ORDER",
    "age": 37,
    "battingStyle": "Right-hand tactical batter",
    "bowlingStyle": "Right-arm chessmaster offspin & carrom ball",
    "basePrice": 20000000,
    "image": "/players/ravichandran-ashwin.jpg",
    "stats": {
      "matches": 212,
      "runs": 800,
      "highestScore": "50",
      "wickets": 180,
      "bestBowling": "4/34",
      "strikeRate": 118,
      "economy": 7.12
    }
  },
  {
    "name": "Shashank Singh",
    "country": "India",
    "isOverseas": false,
    "role": "BATTER",
    "category": "UNCAPPED",
    "isCapped": false,
    "auctionSet": "UBA1",
    "bowlingType": "NONE",
    "battingPosition": "FINISHER",
    "age": 32,
    "battingStyle": "Right-hand fearless power finisher",
    "bowlingStyle": "Right-arm medium",
    "basePrice": 4000000,
    "image": "/players/shashank-singh.jpg",
    "stats": {
      "matches": 24,
      "runs": 423,
      "highestScore": "68*",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 164.7,
      "economy": 0
    }
  },
  {
    "name": "Ashutosh Sharma",
    "country": "India",
    "isOverseas": false,
    "role": "BATTER",
    "category": "UNCAPPED",
    "isCapped": false,
    "auctionSet": "UBA1",
    "bowlingType": "NONE",
    "battingPosition": "FINISHER",
    "age": 25,
    "battingStyle": "Right-hand sweep-and-pull powerhouse",
    "bowlingStyle": "Right-arm medium",
    "basePrice": 3000000,
    "image": "/players/ashutosh-sharma.jpg",
    "stats": {
      "matches": 11,
      "runs": 189,
      "highestScore": "61",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 177.2,
      "economy": 0
    }
  },
  {
    "name": "Sameer Rizvi",
    "country": "India",
    "isOverseas": false,
    "role": "BATTER",
    "category": "UNCAPPED",
    "isCapped": false,
    "auctionSet": "UBA1",
    "bowlingType": "NONE",
    "battingPosition": "MIDDLE_ORDER",
    "age": 20,
    "battingStyle": "Right-hand clean six hitter",
    "bowlingStyle": "Right-arm offbreak",
    "basePrice": 5000000,
    "image": "/players/sameer-rizvi.jpg",
    "stats": {
      "matches": 8,
      "runs": 51,
      "highestScore": "21",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 118.6,
      "economy": 0
    }
  },
  {
    "name": "Angkrish Raghuvanshi",
    "country": "India",
    "isOverseas": false,
    "role": "BATTER",
    "category": "UNCAPPED",
    "isCapped": false,
    "auctionSet": "UBA1",
    "bowlingType": "NONE",
    "battingPosition": "TOP_ORDER",
    "age": 19,
    "battingStyle": "Right-hand elegant teenage sensation",
    "bowlingStyle": "Slow left-arm orthodox",
    "basePrice": 3000000,
    "image": "/players/angkrish-raghuvanshi.jpg",
    "stats": {
      "matches": 10,
      "runs": 163,
      "highestScore": "54",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 155.2,
      "economy": 0
    }
  },
  {
    "name": "Nehal Wadhera",
    "country": "India",
    "isOverseas": false,
    "role": "BATTER",
    "category": "UNCAPPED",
    "isCapped": false,
    "auctionSet": "UBA1",
    "bowlingType": "NONE",
    "battingPosition": "MIDDLE_ORDER",
    "age": 23,
    "battingStyle": "Left-hand aggressive middle-order striker",
    "bowlingStyle": "Right-arm legbreak",
    "basePrice": 4000000,
    "image": "/players/nehal-wadhera.png",
    "stats": {
      "matches": 20,
      "runs": 350,
      "highestScore": "64",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 145.2,
      "economy": 0
    }
  },
  {
    "name": "Vaibhav Suryavanshi",
    "country": "India",
    "isOverseas": false,
    "role": "BATTER",
    "category": "UNCAPPED",
    "isCapped": false,
    "auctionSet": "UBA2",
    "bowlingType": "SPIN",
    "battingPosition": "TOP_ORDER",
    "age": 13,
    "battingStyle": "Left-hand fearless teenage prodigy (youngest IPL auction buy)",
    "bowlingStyle": "Slow left-arm orthodox",
    "basePrice": 3000000,
    "image": "/players/vaibhav-suryavanshi.jpg",
    "stats": {
      "matches": 8,
      "runs": 280,
      "highestScore": "104",
      "wickets": 1,
      "bestBowling": "1/18",
      "strikeRate": 158.4,
      "economy": 8.2
    }
  },
  {
    "name": "Ayush Mhatre",
    "country": "India",
    "isOverseas": false,
    "role": "BATTER",
    "category": "UNCAPPED",
    "isCapped": false,
    "auctionSet": "UBA2",
    "bowlingType": "SPIN",
    "battingPosition": "TOP_ORDER",
    "age": 17,
    "battingStyle": "Right-hand Mumbai opening sensation",
    "bowlingStyle": "Right-arm offbreak",
    "basePrice": 3000000,
    "image": "/players/ayush-mhatre.png",
    "stats": {
      "matches": 9,
      "runs": 532,
      "highestScore": "176",
      "wickets": 3,
      "bestBowling": "2/22",
      "strikeRate": 146.2,
      "economy": 7.9
    }
  },
  {
    "name": "Ramandeep Singh",
    "country": "India",
    "isOverseas": false,
    "role": "ALL_ROUNDER",
    "category": "UNCAPPED",
    "isCapped": false,
    "auctionSet": "UAL1",
    "bowlingType": "PACE",
    "battingPosition": "FINISHER",
    "age": 27,
    "battingStyle": "Right-hand lightning death striker",
    "bowlingStyle": "Right-arm medium-fast",
    "basePrice": 4000000,
    "image": "/players/ramandeep-singh.jpg",
    "stats": {
      "matches": 19,
      "runs": 170,
      "highestScore": "35*",
      "wickets": 6,
      "bestBowling": "3/20",
      "strikeRate": 188.8,
      "economy": 8.9
    }
  },
  {
    "name": "Naman Dhir",
    "country": "India",
    "isOverseas": false,
    "role": "ALL_ROUNDER",
    "category": "UNCAPPED",
    "isCapped": false,
    "auctionSet": "UAL1",
    "bowlingType": "SPIN",
    "battingPosition": "TOP_ORDER",
    "age": 24,
    "battingStyle": "Right-hand explosive strokeplayer",
    "bowlingStyle": "Right-arm offbreak",
    "basePrice": 3000000,
    "image": "/players/naman-dhir.jpg",
    "stats": {
      "matches": 7,
      "runs": 140,
      "highestScore": "62*",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 177.2,
      "economy": 0
    }
  },
  {
    "name": "Shahrukh Khan",
    "country": "India",
    "isOverseas": false,
    "role": "ALL_ROUNDER",
    "category": "UNCAPPED",
    "isCapped": false,
    "auctionSet": "UAL1",
    "bowlingType": "SPIN",
    "battingPosition": "FINISHER",
    "age": 28,
    "battingStyle": "Right-hand ferocious ball striker",
    "bowlingStyle": "Right-arm offbreak",
    "basePrice": 4000000,
    "image": "/players/shahrukh-khan.jpg",
    "stats": {
      "matches": 40,
      "runs": 553,
      "highestScore": "58",
      "wickets": 1,
      "bestBowling": "1/12",
      "strikeRate": 139.6,
      "economy": 9.1
    }
  },
  {
    "name": "Abishek Porel",
    "country": "India",
    "isOverseas": false,
    "role": "WICKET_KEEPER",
    "category": "UNCAPPED",
    "isCapped": false,
    "auctionSet": "UWK1",
    "bowlingType": "NONE",
    "battingPosition": "TOP_ORDER",
    "age": 21,
    "battingStyle": "Left-hand fearless sparkplug",
    "bowlingStyle": "None",
    "basePrice": 3000000,
    "image": "/players/abishek-porel.jpg",
    "stats": {
      "matches": 18,
      "runs": 360,
      "highestScore": "65",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 154.5,
      "economy": 0
    }
  },
  {
    "name": "Kumar Kushagra",
    "country": "India",
    "isOverseas": false,
    "role": "WICKET_KEEPER",
    "category": "UNCAPPED",
    "isCapped": false,
    "auctionSet": "UWK1",
    "bowlingType": "NONE",
    "battingPosition": "MIDDLE_ORDER",
    "age": 19,
    "battingStyle": "Right-hand big hitting prodigy",
    "bowlingStyle": "None",
    "basePrice": 3000000,
    "image": "/players/kumar-kushagra.png",
    "stats": {
      "matches": 4,
      "runs": 3,
      "highestScore": "2",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 60,
      "economy": 0
    }
  },
  {
    "name": "Robin Minz",
    "country": "India",
    "isOverseas": false,
    "role": "WICKET_KEEPER",
    "category": "UNCAPPED",
    "isCapped": false,
    "auctionSet": "UWK1",
    "bowlingType": "NONE",
    "battingPosition": "FINISHER",
    "age": 21,
    "battingStyle": "Left-hand explosive tribal gem",
    "bowlingStyle": "Slow left-arm orthodox",
    "basePrice": 3000000,
    "image": "/players/robin-minz.jpg",
    "stats": {
      "matches": 0,
      "runs": 0,
      "highestScore": "0",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 140,
      "economy": 0
    }
  },
  {
    "name": "Urvil Patel",
    "country": "India",
    "isOverseas": false,
    "role": "WICKET_KEEPER",
    "category": "UNCAPPED",
    "isCapped": false,
    "auctionSet": "UWK2",
    "bowlingType": "NONE",
    "battingPosition": "TOP_ORDER",
    "age": 26,
    "battingStyle": "Right-hand explosive keeper-opener (28-ball T20 hundred)",
    "bowlingStyle": "None",
    "basePrice": 3000000,
    "image": "/players/urvil-patel.jpg",
    "stats": {
      "matches": 45,
      "runs": 1150,
      "highestScore": "115*",
      "wickets": 0,
      "bestBowling": "0/0",
      "strikeRate": 174.6,
      "economy": 0
    }
  },
  {
    "name": "Mayank Yadav",
    "country": "India",
    "isOverseas": false,
    "role": "BOWLER",
    "category": "UNCAPPED",
    "isCapped": false,
    "auctionSet": "UFA1",
    "bowlingType": "PACE",
    "battingPosition": "LOWER_ORDER",
    "age": 22,
    "battingStyle": "Right-hand bat",
    "bowlingStyle": "Right-arm 156.7 km/h supersonic missile",
    "basePrice": 4000000,
    "image": "/players/mayank-yadav.jpg",
    "stats": {
      "matches": 4,
      "runs": 0,
      "highestScore": "0",
      "wickets": 7,
      "bestBowling": "3/14",
      "strikeRate": 15,
      "economy": 6.98
    }
  },
  {
    "name": "Harshit Rana",
    "country": "India",
    "isOverseas": false,
    "role": "BOWLER",
    "category": "UNCAPPED",
    "isCapped": false,
    "auctionSet": "UFA1",
    "bowlingType": "PACE",
    "battingPosition": "LOWER_ORDER",
    "age": 22,
    "battingStyle": "Right-hand bat",
    "bowlingStyle": "Right-arm aggressive champion quick with deadly slower balls",
    "basePrice": 4000000,
    "image": "/players/harshit-rana.jpg",
    "stats": {
      "matches": 21,
      "runs": 32,
      "highestScore": "12*",
      "wickets": 25,
      "bestBowling": "3/24",
      "strikeRate": 60,
      "economy": 8.85
    }
  },
  {
    "name": "Yash Dayal",
    "country": "India",
    "isOverseas": false,
    "role": "BOWLER",
    "category": "UNCAPPED",
    "isCapped": false,
    "auctionSet": "UFA1",
    "bowlingType": "PACE",
    "battingPosition": "LOWER_ORDER",
    "age": 26,
    "battingStyle": "Left-hand bat",
    "bowlingStyle": "Left-arm swing & final-over hero",
    "basePrice": 4000000,
    "image": "/players/yash-dayal.jpg",
    "stats": {
      "matches": 28,
      "runs": 5,
      "highestScore": "4*",
      "wickets": 28,
      "bestBowling": "3/20",
      "strikeRate": 50,
      "economy": 9.2
    }
  },
  {
    "name": "Vaibhav Arora",
    "country": "India",
    "isOverseas": false,
    "role": "BOWLER",
    "category": "UNCAPPED",
    "isCapped": false,
    "auctionSet": "UFA1",
    "bowlingType": "PACE",
    "battingPosition": "LOWER_ORDER",
    "age": 26,
    "battingStyle": "Right-hand bat",
    "bowlingStyle": "Right-arm sharp seam & outswinger",
    "basePrice": 3000000,
    "image": "/players/vaibhav-arora.jpg",
    "stats": {
      "matches": 20,
      "runs": 12,
      "highestScore": "6",
      "wickets": 21,
      "bestBowling": "3/27",
      "strikeRate": 45,
      "economy": 8.95
    }
  },
  {
    "name": "Mohsin Khan",
    "country": "India",
    "isOverseas": false,
    "role": "BOWLER",
    "category": "UNCAPPED",
    "isCapped": false,
    "auctionSet": "UFA2",
    "bowlingType": "PACE",
    "battingPosition": "LOWER_ORDER",
    "age": 25,
    "battingStyle": "Left-hand bat",
    "bowlingStyle": "Left-arm tall bounce pacer",
    "basePrice": 4000000,
    "image": "/players/mohsin-khan.jpg",
    "stats": {
      "matches": 24,
      "runs": 33,
      "highestScore": "13*",
      "wickets": 27,
      "bestBowling": "4/16",
      "strikeRate": 40,
      "economy": 8.15
    }
  },
  {
    "name": "Suyash Sharma",
    "country": "India",
    "isOverseas": false,
    "role": "BOWLER",
    "category": "UNCAPPED",
    "isCapped": false,
    "auctionSet": "USP1",
    "bowlingType": "SPIN",
    "battingPosition": "LOWER_ORDER",
    "age": 21,
    "battingStyle": "Right-hand bat",
    "bowlingStyle": "Right-arm rapid legbreak googly mystery",
    "basePrice": 3000000,
    "image": "/players/suyash-sharma.png",
    "stats": {
      "matches": 13,
      "runs": 0,
      "highestScore": "0",
      "wickets": 10,
      "bestBowling": "3/30",
      "strikeRate": 35,
      "economy": 8.23
    }
  },
  {
    "name": "Manav Suthar",
    "country": "India",
    "isOverseas": false,
    "role": "BOWLER",
    "category": "UNCAPPED",
    "isCapped": false,
    "auctionSet": "USP1",
    "bowlingType": "SPIN",
    "battingPosition": "LOWER_ORDER",
    "age": 22,
    "battingStyle": "Left-hand bat",
    "bowlingStyle": "Slow left-arm classical spinner",
    "basePrice": 3000000,
    "image": "/players/manav-suthar.jpg",
    "stats": {
      "matches": 2,
      "runs": 1,
      "highestScore": "1",
      "wickets": 1,
      "bestBowling": "1/26",
      "strikeRate": 20,
      "economy": 7.8
    }
  },
  {
    "name": "Swapnil Singh",
    "country": "India",
    "isOverseas": false,
    "role": "ALL_ROUNDER",
    "category": "UNCAPPED",
    "isCapped": false,
    "auctionSet": "USP1",
    "bowlingType": "SPIN",
    "battingPosition": "MIDDLE_ORDER",
    "age": 33,
    "battingStyle": "Right-hand handy lower order bat",
    "bowlingStyle": "Slow left-arm orthodox powerplay wicket-taker",
    "basePrice": 3000000,
    "image": "/players/swapnil-singh.jpg",
    "stats": {
      "matches": 15,
      "runs": 68,
      "highestScore": "18",
      "wickets": 9,
      "bestBowling": "2/28",
      "strikeRate": 130,
      "economy": 8.6
    }
  }
];

module.exports = {
  teamsData,
  playersData
};
